-- Prison Chaplains and Justice Worker Organizations
-- SQL INSERT statements for organizations focused on prison ministry and criminal justice

INSERT INTO organizations (id, name, description, website, category, focus_area, donation_url, established_year) VALUES
(1, 'Kairos Prison Ministry International', 'Ecumenical Christian prison ministry providing transformational three-day retreats and ongoing support programs for incarcerated individuals and their families', 'https://www.kairosprisons.org', 'prison_ministry', 'incarcerated_support', 'https://www.kairosprisons.org/donate', 1976),
(2, 'Emmaus Ministries', 'Provides direct support, mentorship, and reentry services for formerly incarcerated individuals transitioning to life after prison', 'https://www.emmaus-ministries.org', 'reentry_services', 'prisoner_reentry', 'https://www.emmaus-ministries.org/donate', 1992),
(3, 'Prison Fellowship International', 'Christian organization working to restore justice, reduce incarceration rates, and support victims and offenders through chaplaincy and advocacy programs', 'https://www.prisonfellowship.org', 'prison_ministry', 'justice_advocacy', 'https://www.prisonfellowship.org/ways-to-give', 1976),
(4, 'Interfaith Criminal Justice Initiative', 'Multi-faith network of prison chaplains and religious workers promoting rehabilitation and spiritual care within correctional systems', 'https://www.icji.org', 'chaplaincy_network', 'chaplaincy_services', 'https://www.icji.org/support', 2005),
(5, 'JustLeadership USA', 'National organization led by formerly incarcerated people advocating for justice reform and supporting those impacted by incarceration', 'https://www.justleadershipusa.org', 'justice_advocacy', 'criminal_justice_reform', 'https://www.justleadershipusa.org/donate', 2001),
(6, 'The Sentencing Project', 'Research and advocacy organization promoting evidence-based criminal justice policies with chaplaincy partnership networks', 'https://www.sentencingproject.org', 'advocacy_research', 'sentencing_reform', 'https://www.sentencingproject.org/donate', 1986),
(7, 'Worth Rises Prison Ministry', 'Faith-based organization providing spiritual guidance, educational programs, and mentorship to incarcerated individuals across multiple state systems', 'https://www.worthrises.org', 'prison_ministry', 'spiritual_guidance', 'https://www.worthrises.org/support', 2008),
(8, 'Streets.org Prison Justice Network', 'Online resource and advocacy platform connecting prison chaplains, justice workers, and volunteers with training, resources, and community support', 'https://streets.org', 'justice_network', 'chaplaincy_resources', 'https://streets.org/donate', 2003),
(9, 'Bridges to Life', 'Victim-offender reconciliation and crime prevention program bringing together crime victims, community members, and individuals who have committed crimes', 'https://www.bridgestolife.org', 'restorative_justice', 'victim_offender_reconciliation', 'https://www.bridgestolife.org/donate', 1997),
(10, 'The Fortune Society', 'NYC-based organization providing comprehensive services for formerly incarcerated people including counseling, employment, and advocacy with chaplaincy partnerships', 'https://www.fortunesociety.org', 'reentry_services', 'comprehensive_reentry', 'https://www.fortunesociety.org/donate', 1967);
