-- Navigators Staff, Discipleship Trainers, and Local Chapter Leaders
-- Organizational directory with discipleship training networks and local ministry leader profiles

INSERT INTO scout_candidates (id, name, email, phone, position, role_type, organization, region, status, bio, focus_area, created_at) VALUES
(1, 'Mark Richardson', 'mark.richardson@navigators.org', '(303) 555-0401', 'Regional Director', 'director', 'The Navigators', 'Rocky Mountain', 'active', 'Leading discipleship and multiplication across the Rocky Mountain region with focus on campus and young professional ministry', 'campus_ministry', NOW()),
(2, 'Susan Chen', 'susan.chen@navigators.org', '(415) 555-0402', 'Discipleship Trainer', 'trainer', 'The Navigators', 'Northern California', 'active', 'Equipping disciple-makers through intensive one-on-one and small group training programs, specializing in spiritual formation and leadership development', 'discipleship_training', NOW()),
(3, 'James Williams', 'james.williams@navigators.org', '(713) 555-0403', 'Houston Chapter Leader', 'chapter_leader', 'The Navigators', 'Texas', 'active', 'Overseeing local chapter operations and coordinating weekly discipleship groups across Houston metropolitan area', 'local_ministry', NOW()),
(4, 'Patricia Lopez', 'patricia.lopez@navigators.org', '(206) 555-0404', 'Seattle Campus Coordinator', 'staff', 'The Navigators', 'Pacific Northwest', 'active', 'Directing campus ministry initiatives at University of Washington and Seattle Pacific University with emphasis on student leadership development', 'campus_ministry', NOW()),
(5, 'David Thompson', 'david.thompson@navigators.org', '(404) 555-0405', 'Atlanta Discipleship Director', 'trainer', 'The Navigators', 'Southeast', 'active', 'Designing and implementing discipleship curricula for young professionals and marketplace leaders in the Atlanta area', 'discipleship_training', NOW()),
(6, 'Elizabeth Martinez', 'elizabeth.martinez@navigators.org', '(212) 555-0406', 'New York Metro Chapter Leader', 'chapter_leader', 'The Navigators', 'Northeast', 'active', 'Planting and nurturing discipleship communities across Manhattan, Brooklyn, and surrounding boroughs with focus on urban professionals', 'local_ministry', NOW()),
(7, 'Robert Kim', 'robert.kim@navigators.org', '(801) 555-0407', 'Salt Lake City Regional Trainer', 'trainer', 'The Navigators', 'Mountain West', 'active', 'Training discipleship leaders and coordinating regional conferences for multiplication and spiritual development across Utah and surrounding states', 'discipleship_training', NOW()),
(8, 'Jennifer Foster', 'jennifer.foster@navigators.org', '(614) 555-0408', 'Columbus Chapter Leader', 'chapter_leader', 'The Navigators', 'Midwest', 'active', 'Leading local ministry operations and fostering discipleship networks among Ohio State students and young professionals in central Ohio', 'local_ministry', NOW());
